spring:
    application:
        name: smodel-hystrix

server:
    port: 10002 #启动端口

security:
    user:
        name: skg
        password: 123456
        role: USER
eureka:
     instance:
        preferIpAddress: true
        lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
        lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://localhost:10000/eureka/
        healthcheck:
           enabled: true